language: php

sudo: false

php:
    - 7.0
    - 7.1

cache:
    directories:
        - $HOME/.composer/cache

#env: PDO_DSN="mysql:host=localhost;dbname=bav" PDO_USER=travis

install:
    - composer install

#before_script:
#    - mysql -e 'SET @@GLOBAL.wait_timeout=1200'
#    - mysql -e 'create database bav;'
#    - php tests/bin/test-install.php

script:
    - vendor/bin/phpunit -c phpunit.xml
    - vendor/bin/phpunit -c phpunit-integration.xml --testsuite IntegrationTests
#    - vendor/bin/phpunit --exclude-group large tests/unit-large/
#    - vendor/bin/phpcs --standard=PSR2 classes/ bin/ docs/example.php tests/classes/ tests/bin/ tests/bootstrap.php

