language: php

php:
    - 5.6
    - 5.5
    - 5.4
    - 5.3

cache:
    directories:
        - $HOME/.composer/cache

env: PDO_DSN="mysql:host=localhost;dbname=bav" PDO_USER=travis

install:
    - composer require squizlabs/php_codesniffer

before_script:
    - mysql -e 'SET @@GLOBAL.wait_timeout=1200'
    - mysql -e 'create database bav;'
    - php tests/bin/test-install.php

script:
    - phpunit tests/unit/
    - phpunit --exclude-group large tests/unit-large/
    - vendor/bin/phpcs --standard=PSR2 classes/ bin/ docs/example.php tests/classes/ tests/bin/ tests/bootstrap.php

