language: php

php:
    - 5.5
    - 5.4
    - 5.3

env: PDO_DSN="mysql:host=localhost;dbname=bav" PDO_USER=travis

install:
    - pyrus install pear/PHP_CodeSniffer
    - phpenv rehash
    - sudo apt-get install parallel

before_script:
    - composer --prefer-source --dev install
    - mysql -e 'SET @@GLOBAL.wait_timeout=1200'
    - mysql -e 'create database bav;'
    - php tests/bin/test-install.php

script:
    - find tests/ -type f -name "*Test.php" | parallel phpunit --exclude-group large {}
    - phpcs --standard=PSR2 classes/ bin/ docs/example.php tests/classes/ tests/bin/ tests/bootstrap.php

